
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author veloso
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        zoo = new Zoo();
        buscar();
    }
    
    Zoo zoo = new Zoo();
    
    public void limpar(){
        jCBVoar.setSelectedItem("SIM");
        jTFAltura.setText("");
        jTFEnvergadura.setText("");
        jTFIdade.setText("");
        jTFNome.setText("");
        jTFPeso.setText("");
        jTFVelocidade.setText("");
    }
    
    public void buscar(){
        Animal[] animais = zoo.getAnimais();
        listaAnimais(animais);
        limpar();
    }
    
    public void listaAnimais(Animal[] animais){
        DefaultTableModel dtm = (DefaultTableModel) jTAnimais.getModel();
        
        ((DefaultTableModel) jTAnimais.getModel()).setNumRows(0);
        jTAnimais.updateUI();
        
        for(Animal a: animais){
                if(a!=null)
                    dtm.addRow(new Object[]{a.getNome()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCBTipoAnimal = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTFIdade = new javax.swing.JTextField();
        jTFVelocidade = new javax.swing.JTextField();
        jTFEnvergadura = new javax.swing.JTextField();
        jCBVoar = new javax.swing.JComboBox<>();
        jTFNome = new javax.swing.JTextField();
        jBSalvar = new javax.swing.JButton();
        jBBuscar = new javax.swing.JButton();
        jBExcluir = new javax.swing.JButton();
        jBCalcula = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTFPeso = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAnimais = new javax.swing.JTable();
        jLAlturaRaca = new javax.swing.JLabel();
        jTFAltura = new javax.swing.JTextField();
        jBTeste = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jLabel1.setText("Avaliação de POO - ZOO");

        jLabel2.setText("Tipo do Animal");

        jCBTipoAnimal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pássaro", "Cachorro", "Cavalo" }));
        jCBTipoAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBTipoAnimalActionPerformed(evt);
            }
        });

        jLabel3.setText("Nome:");

        jLabel4.setText("Idade:");

        jLabel5.setText("Velocidade:");

        jLabel6.setText("Envergadura:");

        jLabel7.setText("Capacidade de voar:");

        jCBVoar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SIM", "NÃO" }));

        jBSalvar.setText("Salvar");
        jBSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalvarActionPerformed(evt);
            }
        });

        jBBuscar.setText("Buscar");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        jBExcluir.setText("Excluir");
        jBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirActionPerformed(evt);
            }
        });

        jBCalcula.setText("Calcula");
        jBCalcula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCalculaActionPerformed(evt);
            }
        });

        jLabel8.setText("Peso:");

        jTAnimais.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTAnimais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTAnimaisMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTAnimais);

        jLAlturaRaca.setText("Altura:");

        jBTeste.setText("Teste");
        jBTeste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTesteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jCBTipoAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(jTFNome)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel8)
                            .addGap(18, 18, 18)
                            .addComponent(jTFPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)
                                .addComponent(jLAlturaRaca))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTFIdade, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                                        .addComponent(jTFVelocidade))
                                    .addGap(42, 42, 42)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel6))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTFEnvergadura)
                                        .addComponent(jCBVoar, 0, 90, Short.MAX_VALUE)))
                                .addComponent(jTFAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jBTeste, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBSalvar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBCalcula, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jCBTipoAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jTFPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jTFIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFEnvergadura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jTFVelocidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCBVoar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLAlturaRaca)
                            .addComponent(jTFAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBTeste)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBSalvar)
                            .addComponent(jBBuscar)
                            .addComponent(jBExcluir)
                            .addComponent(jBCalcula))
                        .addGap(38, 38, 38))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        // TODO add your handling code here:
        Animal[] animais = zoo.getAnimais();
        listaAnimais(animais);
        limpar();
    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jBSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalvarActionPerformed
         // TODO add your handling code here
         boolean resultado = false;
         String nome = jTFNome.getText();
         float peso = Float.valueOf(jTFPeso.getText());
         if(jCBTipoAnimal.getSelectedIndex()==0){
             Boolean voa = (jCBVoar.getSelectedItem().equals("SIM"));
             int envergadura = Integer.parseInt(jTFEnvergadura.getText());
             Passaro p = new Passaro(nome, peso, voa, envergadura);
             resultado = zoo.adicionarAnimal(p);
         }else{
                int idade = Integer.parseInt(jTFIdade.getText());
                int velocidade = Integer.parseInt(jTFVelocidade.getText());
                if(jCBTipoAnimal.getSelectedIndex()==1){
                    float altura = Float.parseFloat(jTFAltura.getText());
                    Cachorro ch = new Cachorro(nome, peso, idade, velocidade, altura);
                    resultado = zoo.adicionarAnimal(ch);
                }
                if(jCBTipoAnimal.getSelectedIndex()==2){
                    String raca = jTFAltura.getText();
                    Cavalo cv = new Cavalo(nome, peso, idade, velocidade, raca);
                    resultado = zoo.adicionarAnimal(cv);
                }
             
         }
         if (resultado)
             JOptionPane.showMessageDialog(null, "Animal salvo com sucesso");
         else
             JOptionPane.showMessageDialog(null, "Falha no salvamento");
         limpar();
         buscar();
    }//GEN-LAST:event_jBSalvarActionPerformed

    private void jBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirActionPerformed
        // TODO add your handling code here:
        String nome = jTFNome.getText();
        float peso = Float.valueOf(jTFPeso.getText());
        int tipo;
        if(jCBTipoAnimal.getSelectedItem().equals("Pássaro")){
            tipo = 1;
        }else{
            if(jCBTipoAnimal.getSelectedItem().equals("Cachorro")){
                tipo = 2;
            }else{
                tipo = 3;
            }
        }
        Animal animal =  new Animal(nome, peso, tipo);
        if(zoo.excluirAnimal(animal))
            JOptionPane.showMessageDialog(null, "Excluído com sucesso");
        else
            JOptionPane.showMessageDialog(null, "Animal não encontrado");
        limpar();
        buscar();
    }//GEN-LAST:event_jBExcluirActionPerformed

    private void jBCalculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCalculaActionPerformed
        // TODO add your handling code here:
        String nome = jTFNome.getText();
        float peso = Float.valueOf(jTFPeso.getText());
        int tipo;
        if(jCBTipoAnimal.getSelectedItem().equals("Pássaro")){
            tipo = 1;
        }else{
            if(jCBTipoAnimal.getSelectedItem().equals("Cachorro")){
                tipo = 2;
            }else{
                tipo = 3;
            }
        }
        Animal animal =  new Animal(nome, peso, tipo);
        animal = zoo.buscaAnimal(animal.getNome());
        JOptionPane.showMessageDialog(null, zoo.calcula(animal));
    }//GEN-LAST:event_jBCalculaActionPerformed

    private void jCBTipoAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBTipoAnimalActionPerformed
        // TODO add your handling code here:
        if(jCBTipoAnimal.getSelectedItem().equals("Pássaro")){
            jCBVoar.setEnabled(true);
            jTFAltura.setEnabled(false);
            jTFEnvergadura.setEnabled(true);
            jTFIdade.setEnabled(false);
            jTFNome.setEnabled(true);
            jTFPeso.setEnabled(true);
            jTFVelocidade.setEnabled(false);
        }
        
        if(jCBTipoAnimal.getSelectedItem().equals("Cachorro")){
            jCBVoar.setEnabled(false);
            jTFAltura.setEnabled(true);
            jTFEnvergadura.setEnabled(false);
            jTFIdade.setEnabled(true);
            jTFNome.setEnabled(true);
            jTFPeso.setEnabled(true);
            jTFVelocidade.setEnabled(true);
            jLAlturaRaca.setText("Altura");
        }
        
        if(jCBTipoAnimal.getSelectedItem().equals("Cavalo")){
            jCBVoar.setEnabled(false);
            jTFAltura.setEnabled(true);
            jTFEnvergadura.setEnabled(false);
            jTFIdade.setEnabled(true);
            jTFNome.setEnabled(true);
            jTFPeso.setEnabled(true);
            jTFVelocidade.setEnabled(true);
            jLAlturaRaca.setText("Raça   ");
        }
        
    }//GEN-LAST:event_jCBTipoAnimalActionPerformed

    private void jTAnimaisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTAnimaisMouseClicked
        // TODO add your handling code here:
        int linha = jTAnimais.getSelectedRow();
        String nome = (String) jTAnimais.getValueAt(linha, 0);
        Animal a = zoo.buscaAnimal(nome);
        if (a==null) return;
        if(a.getTipo()==1){
            Passaro p = (Passaro) a;
            limpar();
            
            jCBTipoAnimal.setSelectedIndex(0);
            
            jCBVoar.setEnabled(true);
            jTFAltura.setEnabled(false);
            jTFEnvergadura.setEnabled(true);
            jTFIdade.setEnabled(false);
            jTFNome.setEnabled(true);
            jTFPeso.setEnabled(true);
            jTFVelocidade.setEnabled(false);
            
            if(p.getVoa()) 
                jCBVoar.setSelectedIndex(0);
            else
                jCBVoar.setSelectedIndex(1);
            jTFEnvergadura.setText(String.valueOf(p.getEnvergadura()));
            jTFNome.setText(p.getNome());
            jTFPeso.setText(String.valueOf(p.getPeso()));
        }
        
        if(a.getTipo()==2){
            Cachorro ch = (Cachorro) a;
            limpar();
            
            jCBTipoAnimal.setSelectedIndex(1);
            
            jCBVoar.setEnabled(false);
            jTFAltura.setEnabled(true);
            jTFEnvergadura.setEnabled(false);
            jTFIdade.setEnabled(true);
            jTFNome.setEnabled(true);
            jTFPeso.setEnabled(true);
            jTFVelocidade.setEnabled(true);
            jLAlturaRaca.setText("Altura");
            
            jTFAltura.setText(String.valueOf(ch.getAltura()));
            jTFIdade.setText(String.valueOf(ch.getIdade()));
            jTFNome.setText(ch.getNome());
            jTFPeso.setText(String.valueOf(ch.getPeso()));
            jTFVelocidade.setText(String.valueOf(ch.getVelocidade()));
        }
        
        if(a.getTipo()==3){ 
            Cavalo cv = (Cavalo) a;
            limpar();
            
            jCBTipoAnimal.setSelectedIndex(2);
            
            jCBVoar.setEnabled(false);
            jTFAltura.setEnabled(true);
            jTFEnvergadura.setEnabled(false);
            jTFIdade.setEnabled(true);
            jTFNome.setEnabled(true);
            jTFPeso.setEnabled(true);
            jTFVelocidade.setEnabled(true);
            jLAlturaRaca.setText("Raça   ");
            
            jTFAltura.setText(cv.getRaca());
            jTFIdade.setText(String.valueOf(cv.getIdade()));
            jTFNome.setText(cv.getNome());
            jTFPeso.setText(String.valueOf(cv.getPeso()));
            jTFVelocidade.setText(String.valueOf(cv.getVelocidade()));
        }
    }//GEN-LAST:event_jTAnimaisMouseClicked

    private void jBTesteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTesteActionPerformed
        // TODO add your handling code here:
        zoo = new Zoo();
        Cachorro ch = new Cachorro("Rex", 4.0, 10, 8, 7.0);
        zoo.adicionarAnimal(ch);
        Passaro p = new Passaro("Piu Piu", 0.3, true, 10);
        zoo.adicionarAnimal(p);
        Cavalo cv = new Cavalo("Alazao", 800.0, 24, 45, "Manga Larga");
        zoo.adicionarAnimal(cv);
        Cachorro ch1 = new Cachorro("Bolt", 6.0, 8, 6, 10.0);
        zoo.adicionarAnimal(ch1);
        Passaro p1 = new Passaro("flink", 0.4, true, 8);
        zoo.adicionarAnimal(p1);
        Cavalo cv1 = new Cavalo("Pangare", 900.0, 18, 20, "Campolino");
        zoo.adicionarAnimal(cv1);
        
    }//GEN-LAST:event_jBTesteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBCalcula;
    private javax.swing.JButton jBExcluir;
    private javax.swing.JButton jBSalvar;
    private javax.swing.JButton jBTeste;
    private javax.swing.JComboBox<String> jCBTipoAnimal;
    private javax.swing.JComboBox<String> jCBVoar;
    private javax.swing.JLabel jLAlturaRaca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTAnimais;
    private javax.swing.JTextField jTFAltura;
    private javax.swing.JTextField jTFEnvergadura;
    private javax.swing.JTextField jTFIdade;
    private javax.swing.JTextField jTFNome;
    private javax.swing.JTextField jTFPeso;
    private javax.swing.JTextField jTFVelocidade;
    // End of variables declaration//GEN-END:variables
}
